apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.example.tag }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-{{ .Values.example.tag }}
  ports:
    - port: {{ .Values.example.port }}
      targetPort: {{ .Values.example.port }}
