apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.example.tag }} 
  labels:
    app: {{ .Release.Name }}-{{ .Values.example.tag }}
spec:
  replicas: {{ .Values.example.replica }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.example.tag }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.example.tag }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.example.image }} 
          image: {{ .Values.example.repo }}/{{ .Values.example.image }}:{{ .Values.example.tagPlain }}
          ports:
            - containerPort: 3000 
              protocol: TCP
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 50m